# Generated by Django 5.0 on 2025-03-31 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
    ]
