# Generated by Django 5.0 on 2025-04-08 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0003_product_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('requirements', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('architect_name', models.CharField(max_length=100)),
                ('architect_number', models.CharField(max_length=15)),
                ('source', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Indiamart', 'Indiamart'), ('Google', 'Google'), ('Reference', 'Reference'), ('Other', 'Other')], max_length=50)),
                ('source_other', models.CharField(blank=True, max_length=100, null=True)),
                ('enquiry_date', models.DateField()),
                ('customer_segment', models.CharField(choices=[('Retail/individual', 'Retail/individual'), ('B2B', 'B2B'), ('Reseller', 'Reseller'), ('Commercial/Corporate', 'Commercial/Corporate')], max_length=50)),
                ('follow_up_date', models.DateField()),
                ('follow_up_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_person', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='kushalapp.product')),
                ('sales_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_person', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, to='kushalapp.service')),
            ],
        ),
    ]
