# Generated by Django 5.0 on 2025-04-08 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0004_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed Win', 'Closed Win'), ('Closed Loss', 'Closed Loss')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_number', models.PositiveIntegerField()),
                ('current_followup_date', models.DateField(auto_now_add=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('customer_visit', models.BooleanField(default=False)),
                ('interested_in', models.CharField(blank=True, choices=[('Product', 'Product'), ('Service', 'Service')], max_length=20)),
                ('onsite_inspection_done', models.BooleanField(default=False)),
                ('quotation_given', models.BooleanField(default=False)),
                ('quotation_amount', models.FloatField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='followup_files/')),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_status', models.CharField(blank=True, choices=[('Win', 'Win'), ('Loss', 'Loss')], max_length=20, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='kushalapp.lead')),
            ],
        ),
    ]
