# Generated by Django 5.0 on 2025-04-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0005_lead_lead_status_followup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['next_followup_date'], 'verbose_name': 'Follow-Up', 'verbose_name_plural': 'Follow-Ups'},
        ),
    ]
