# Generated by Django 5.0 on 2025-04-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0006_alter_followup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='follow_up_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('HOT', 'HOT'), ('WARM', 'WARM'), ('COLD', 'COLD')], default='WARM', max_length=50),
        ),
    ]
