# Generated by Django 5.0 on 2025-04-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0007_lead_follow_up_number_lead_lead_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='follow_up_number',
            new_name='current_followup',
        ),
    ]
