# Generated by Django 5.0 on 2025-04-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0008_rename_follow_up_number_lead_current_followup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='current_followup',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_type',
        ),
        migrations.DeleteModel(
            name='FollowUp',
        ),
    ]
