# Generated by Django 5.0 on 2025-04-08 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0010_followup1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup1',
            old_name='second_followup_date',
            new_name='followup_date',
        ),
        migrations.RemoveField(
            model_name='followup1',
            name='second_followup_person',
        ),
        migrations.AddField(
            model_name='followup1',
            name='close_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='followup1',
            name='followup_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup1',
            name='next_followup_date',
            field=models.DateField(default='2022-04-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followup1',
            name='next_followup_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup2_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup1',
            name='remarks',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FollowUp10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('next_followup_date', models.DateField()),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup3_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('next_followup_date', models.DateField()),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup4_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('next_followup_date', models.DateField()),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup5_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('next_followup_date', models.DateField()),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup6_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('next_followup_date', models.DateField()),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup7_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('next_followup_date', models.DateField()),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup8_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('next_followup_date', models.DateField()),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup9_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('next_followup_date', models.DateField()),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup10_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
