# Generated by Django 5.0 on 2025-04-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0012_rename_follow_up_date_lead_followup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='followup_date',
            new_name='follow_up_date',
        ),
    ]
