# Generated by Django 5.0 on 2025-04-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0013_rename_followup_date_lead_follow_up_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup1',
            name='followup_date',
        ),
        migrations.RemoveField(
            model_name='followup10',
            name='followup_date',
        ),
        migrations.RemoveField(
            model_name='followup2',
            name='followup_date',
        ),
        migrations.RemoveField(
            model_name='followup3',
            name='followup_date',
        ),
        migrations.RemoveField(
            model_name='followup4',
            name='followup_date',
        ),
        migrations.RemoveField(
            model_name='followup5',
            name='followup_date',
        ),
        migrations.RemoveField(
            model_name='followup6',
            name='followup_date',
        ),
        migrations.RemoveField(
            model_name='followup7',
            name='followup_date',
        ),
        migrations.RemoveField(
            model_name='followup8',
            name='followup_date',
        ),
        migrations.RemoveField(
            model_name='followup9',
            name='followup_date',
        ),
    ]
