# Generated by Django 5.0 on 2025-04-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0014_remove_followup1_followup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup1',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
