# Generated by Django 5.0 on 2025-04-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0016_alter_followup2_next_followup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup3',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
